### PR TITLE
fix 7: Implement a Custom Exception Management

### LINKED ISSUE #7: Implement a Custom Exception Management
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Implement a Custom Exception Management class in order to use it while handling exceptions throughout the code base.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by nmarulo**
fix #7

### CODE REVIEW

**Review by evrentan — CHANGES_REQUESTED** [review]
Hi @nmarulo,
Thanks for the pr. Lets have both IOException & WriterException return internal server error as both are internal server errors from business-wise.

**Comment by nmarulo** [comment]
@evrentan 
I have uploaded the requested changes.

**Comment by evrentan** [comment]
Thanks @nmarulo, i have just approved & merged them.

**Review by evrentan — APPROVED** [review]
Thanks for the pr & update :)

**Comment by evrentan** [comment]
@nmarulo, could you also add your name & github account into CONTRIBUTORS.md file as it is in that file & open another pr? Thanks.

**Pull request merged**
