### PR TITLE
Add Dockerfile to run appication inside containter

### LINKED ISSUE #8: Dockerize the Application
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Dockerize the Application.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by ujwalkumar1995**
Hey @evrentan 
Submitting this PR for the issue #8 
I have added a dockerfile to run the application inside the container.
I was able to run the application on 8080 port using below command:
docker run -p 8080:8082 <image-name or id>

Let me know if I need to make any improvement in this.

### CODE REVIEW

**Review by evrentan — CHANGES_REQUESTED** [review]
hi @ujwalkumar1995,
Thanks for the pr, I have done some updates. Could you also please add an argument for jar file so we need to just update that one. Especially when the version is changed.

And also pls add your name to the Credits section in README.md :)

Thanks again.

**Comment by ujwalkumar1995** [comment]
Hi @evrentan 
I have made the suggested changes. Now we can pass the jar file name as an argument while building the image.
Have also provided a default jar name in case no argument is provided.
Please have  a look.

**Review by evrentan — CHANGES_REQUESTED** [review]
Hi @ujwalkumar1995,
That looks great. I will just ask a final change. Pls, also add how to build with args with docker by updating the "Running the Application in Docker" section in README.md file.

Thanks.

**Comment by ujwalkumar1995** [comment]
Hey @evrentan 
I have updated the ReadMe as per your suggestion. Let me know if this is fine.

**Review by evrentan — APPROVED** [review]

**Review by evrentan — APPROVED** [review]

**Comment by evrentan** [comment]
Thanks @ujwalkumar1995 for the contribution, great work 💯 👍🏻

**Pull request merged**
